#!/bin/bash
# Quick publish script

npm run lint &&
npm run test &&
npm run build &&
rm -fr ./src/*.js &&
git commit -a -m "$@" &&
npm version patch -m "$@" &&
git push origin master &&
npm publish

echo Done
